---
name: evcc
version: 0.200.1
slug: evcc
description: EV Charge Controller!
url: https://github.com/evcc-io/evcc
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
panel_icon: mdi:ev-station
panel_admin: false
boot: auto
legacy: true
stage: stable
ingress: true
ingress_port: 7070
init: false
image: evcc/evcc
options: 
  config_file: /config/evcc.yaml
  sqlite_file: /data/evcc.db
schema:
  config_file: str
  sqlite_file: str
host_network: true
map: 
  - type: addon_config
    read_only: False
  - type: homeassistant_config
    read_only: False
uart: true
webui: http://[HOST]:[PORT:7070]/
ports:
  4712/tcp: 4712
  5200/tcp: 5200
  5201/tcp: 5201
  5353/udp: 5353
  7090/udp: 7090
  8887/tcp: 8887
  8899/udp: 8899
  9522/udp: 9522
ports_description:
  4712/tcp: "EEBUS"
  5200/tcp: "Modbus Proxy"
  5201/tcp: "Modbus Proxy (multi port)"
  5353/udp: "Multicast DNS (mDNS)"
  7090/udp: "Keba"
  8887/tcp: "OCPP web socket"
  8899/udp: "Modbus UDP"
  9522/udp: "SMA Speedwire Multicast"
