name: CI

on: 
  # Run on all pushes to all branches
  push:
  
  # Run on all PRs
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Add-on configuration
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6

      - name: 🚀 Run evcc-nightly Add-on Lint
        uses: frenck/action-addon-linter@v2
        with:
          path: "./evcc-nightly"
        # Temporarly allow to pass, even if this step fails in order to implement this linter
        # fix the issues in nightly and merge the changes to main if the changes are working as expected
        continue-on-error: true

      - name: 🚀 Run evcc Add-on Lint
        uses: frenck/action-addon-linter@v2
        with:
          path: "./evcc"
        # Temporarly allow to pass, even if this step fails in order to implement this linter
        # fix the issues in nightly and merge the changes to main if the changes are working as expected
        continue-on-error: true
